default_url_options:
  protcol: 'https'
  host: 'www.alcohol-whisker.com'
#sorcery:
  #google_callback_url: 'https://www.alcohol-whisker.com/oauth/callback?provider=google'
sorcery:
  twitter_callback_url: 'https://www.alcohol-whisker.com/oauth/callback?provider=twitter'